cycle_time_ms = 5
serial_device = "/dev/ttyACM0"
opcua_config_path = "opcua_config.conf"
control_mode = "Tracking"
limit_max_coax = 201574
limit_min_coax = 0
maxspeed_coax = 153600
accel_coax = 205
offset_coax = 0
limit_max_cross = 201574
limit_min_cross = 0
maxspeed_cross = 153600
accel_cross = 205
mock_zaber = true
mock_adc = true
formula_coax = "47.11 - (47.11 - 33.30) / (1.282 - 0.403) * (v1 - 0.403)"
formula_cross = "10"
web_port = 8085
