cycle_time = 250
restart_timeout = 10000
voltage_min = 0.0
voltage_max = 8.5
serial_device = "/dev/ttyACM0"
opcua_config_path = "opcua_config.conf"
backend = "Zaber"
limit_max_coax = 64.0
limit_min_coax = 0.0
maxspeed_coax = 46.5087890625
offset_coax = 0.0
limit_max_cross = 99.9996015625
limit_min_cross = 0.0
maxspeed_cross = 46.5087890625
