cycle_time_ns = 500000000
serial_device = "/dev/ttyACM0"
opcua_config_path = "opcua_config.conf"
control_mode = "Manual"
limit_max_coax = 201574
limit_min_coax = 0
maxspeed_coax = 7
accel_coax = 32768
offset_coax = 0
limit_max_cross = 201574
limit_min_cross = 0
maxspeed_cross = 7
accel_cross = 32768
mock_zaber = false
formula_coax = "64 - (64 - 14) / (v2 - 0.12) * (v1 - 0.12)"
formula_cross = "0"
web_port = 8085
