cycle_time_ns = 10
serial_device = "/dev/ttyACM0"
opcua_config_path = "opcua_config.conf"
control_mode = "Tracking"
limit_max_coax = 129008
limit_min_coax = 34268
maxspeed_coax = 46.5087890625
offset_coax = 0
limit_max_cross = 201574
limit_min_cross = 0
maxspeed_cross = 46.5087890625
formula_coax = "64 - (64 - 17) / (2 - 0.12) * (v1 - 0.12)"
formula_cross = "0"
mock_zaber = false
