cycle_time_ns = 500000
restart_timeout = 10000
voltage_min = 0.12
voltage_max = 2.0
serial_device = "/dev/ttyACM0"
opcua_config_path = "opcua_config.conf"
control_mode = "Manual"
limit_max_coax = 129008
limit_min_coax = 34268
maxspeed_coax = 46.5087890625
offset_coax = 0
limit_max_cross = 201574
limit_min_cross = 0
maxspeed_cross = 46.5087890625
mock_zaber = true
