cycle_time_ns = 1000
serial_device = "/dev/ttyACM0"
opcua_config_path = "opcua_config.conf"
control_mode = "Manual"
limit_max_coax = 129008
limit_min_coax = 34268
maxspeed_coax = 10
accel_coax = 50
offset_coax = 0
limit_max_cross = 201574
limit_min_cross = 0
maxspeed_cross = 46
accel_cross = 50
mock_zaber = true
formula_coax = "64 - (64 - 17) / (1.2 - 0.2) * (v1 - 0.2)"
formula_cross = "0."
