cycle_time_ms = 5
serial_device = "/dev/ttyACM0"
opcua_config_path = "opcua_config.conf"
control_mode = "Manual"
limit_max_coax = 100787
limit_min_coax = 20157
maxspeed_coax = 153600
accel_coax = 205
offset_coax = 0
limit_max_cross = 120945
limit_min_cross = 30236
maxspeed_cross = 153600
accel_cross = 205
mock_zaber = true
mock_adc = true
formula_coax = "v1"
formula_cross = "10"
web_port = 8085
config_path = "test_config.toml"
