name: Rust

on:
  push:
    tags:
      - "v*.*.*"

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    #- name: Run tests
    #  run: cargo test
    - name: Build docker image
      run: docker build -t zaber .
    - name: Build release binary
      run: sh build.sh
    - uses: softprops/action-gh-release@v2
      name: Upload release binary
      with:
        files: target/x86_64-pc-windows-gnu/release/lus_positioning_control.exe
